cam0:
  T_cam_imu:
    [-0.015298425825444856, -0.9998631296939455, 0.006299209942005002, 8.641261161821896e-05,
      7.846780776432638e-05, -0.0063011477419537, -0.999980144492849, -4.966941215770805e-05,
      0.9998829691569251, -0.015297627782246637, 0.00017485470919689772, -0.00011306770424694888,
      0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0018645604002542789, -0.009206711115906055, -0.001490842343490958,
    0.0047045781898403]
  distortion_model: radtan
  intrinsics: [669.2387507702717, 669.6062139634853, 647.4136147885813, 348.40757297218505]
  resolution: [1280, 720]
  rostopic: /zed/left/image_rect_color
  timeshift_cam_imu: -0.03065117695773597
cam1:
  T_cam_imu:
    [-0.016642754591538328, -0.9998393437490949, 0.006656230989468603, -0.062685822672951,
      1.8270936095243773e-05, -0.006657457119676052, -0.9999778387198752, -8.019394325000878e-05,
      0.9998614996017092, -0.01664226415122072, 0.00012906642580154393, -0.0007581427986875548,
      0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
    [0.9999990323751833, -0.00035726932391348155, -0.0013444728798838249, -0.06277240496277349,
     0.0003571960514729939, 0.9999999347073224, -5.47387353674615e-05, -3.056158976215845e-05,
     0.0013444923485705688, 5.4258441996895764e-05, 0.9999990946977619, -0.0006451886829112736,
     0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.0011120079644645446, -0.006192062533471337, -0.0011416874899672696,
    0.004836945809987094]
  distortion_model: radtan
  intrinsics: [669.7077049723667, 669.7830132578491, 648.2500643003343, 348.45508924255745]
  resolution: [1280, 720]
  rostopic: /zed/right/image_rect_color
  timeshift_cam_imu: -0.027537523112180474
